#!/usr/bin/env bash

string_for_replacement="[mysqld]\n\t
	server-id = 1\n\t
	log_bin = /var/log/mysql/mysql-bin.log\n\t
	binlog_do_db = tyrell_corp\n\t
sudo sed -i "s/[mysqld]/$string_for_replacement/" /etc/mysql/mysql.conf.d/mysqld.cnf
sudo systemctl restart mysql
