#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs
# NB: The flag -s creates a symbolic link, -f deletes the existing file and replaces it
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
