#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs
#to make the code sweet and short
sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
pkill -o nginx
