#!/usr/bin/env bash
# To Install the ufw firewall
sudo apt-get update
sudo apt-get install ufw

# To Set the default incoming policy to deny
sudo ufw default deny incoming

# To Allow SSH (port 22)
sudo ufw allow 22/tcp

# To Allow HTTPS (port 443)
sudo ufw allow 443/tcp

# To Allow HTTP (port 80)
sudo ufw allow 80/tcp

#Enable the firewall
sudo ufw disable 
