#!/usr/bin/env bash
# Check if an argument was provided
if [ -z "$1" ]
then
    echo "Error: No user argument provided."
    exit 1
fi
# Run the 'whoami' command under the user specified in the argument
sudo -u "$1" whoami
