#!/usr/bin/env bash
# To make the code fr task 1 shorter and sweet
service nginx stop
chown -R nginx:nginx /var/log/nginx /var/lib/nginx /etc/nginx
sed -i 's/user  nginx;/user nginx nginx;/g' /etc/nginx/nginx.conf
service nginx start
